import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'widgets/globe_of_lcons_widget.dart';
import 'widgets/scale_gauge_widget.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Morteza Developer',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        fontFamily: 'YekanBakh',
      ),
      home: Scaffold(
        // backgroundColor: Colors.black,
        backgroundColor: Color(0xff222222),
        body: SizedBox(
          width: double.infinity,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              SizedBox(height: 120),
              GlobeOfIconsWidget(
                icons: [
                  CupertinoIcons.cloud,
                  CupertinoIcons.chevron_up,
                  CupertinoIcons.bag_fill,
                  CupertinoIcons.arrow_up_doc_fill,
                  CupertinoIcons.camera,
                  CupertinoIcons.bookmark_fill,
                  CupertinoIcons.chevron_back,
                  CupertinoIcons.cloud_sun,
                  CupertinoIcons.circle,
                  CupertinoIcons.battery_0,
                  CupertinoIcons.chat_bubble,
                  CupertinoIcons.chevron_down,
                  CupertinoIcons.cloud_upload_fill,
                  CupertinoIcons.cart,
                  CupertinoIcons.bell,
                  CupertinoIcons.arrow_right,
                  CupertinoIcons.book_fill,
                  CupertinoIcons.cloud_rain_fill,
                  CupertinoIcons.arrow_left_circle_fill,
                  CupertinoIcons.clear,
                  CupertinoIcons.battery_charging,
                  CupertinoIcons.check_mark_circled,
                  CupertinoIcons.arrow_down_doc,
                  CupertinoIcons.briefcase_fill,
                  CupertinoIcons.car_detailed,
                  CupertinoIcons.cloud_snow,
                  CupertinoIcons.chevron_compact_left,
                  CupertinoIcons.circle_fill,
                  CupertinoIcons.book,
                  CupertinoIcons.chat_bubble_2,
                  CupertinoIcons.cloud_download_fill,
                  CupertinoIcons.chevron_right,
                  CupertinoIcons.arrow_up_right,
                  CupertinoIcons.check_mark,
                  CupertinoIcons.alarm_fill,
                  CupertinoIcons.cloud_upload,
                  CupertinoIcons.clear_circled,
                  CupertinoIcons.arrow_down_circle,
                  CupertinoIcons.calendar_today,
                  CupertinoIcons.add_circled,
                  CupertinoIcons.bag_badge_plus,
                  CupertinoIcons.battery_empty,
                  CupertinoIcons.chevron_forward,
                  CupertinoIcons.bookmark,
                  CupertinoIcons.arrow_down_right_circle_fill,
                  CupertinoIcons.battery_full,
                  CupertinoIcons.bag,
                  CupertinoIcons.chat_bubble_fill,
                  CupertinoIcons.add,
                  CupertinoIcons.clock_fill,
                  CupertinoIcons.cloud_snow_fill,
                  CupertinoIcons.cart_fill,
                  CupertinoIcons.bolt_circle,
                  CupertinoIcons.alarm,
                  CupertinoIcons.chat_bubble_2_fill,
                  CupertinoIcons.check_mark_circled_solid,
                  CupertinoIcons.chevron_compact_down,
                  CupertinoIcons.arrow_up_circle,
                  CupertinoIcons.arrow_left,
                  CupertinoIcons.app,
                  CupertinoIcons.bolt_fill,
                  CupertinoIcons.arrow_clockwise,
                  CupertinoIcons.calendar,
                  CupertinoIcons.cloud_rain,
                  CupertinoIcons.chevron_compact_right,
                  CupertinoIcons.bag_badge_minus,
                  CupertinoIcons.arrow_up_doc,
                  CupertinoIcons.arrow_down_left,
                  CupertinoIcons.arrow_up_circle_fill,
                  CupertinoIcons.arrow_down_right,
                  CupertinoIcons.bell_slash_fill,
                  CupertinoIcons.bolt_badge_a,
                  CupertinoIcons.archivebox,
                  CupertinoIcons.chevron_compact_up,
                  CupertinoIcons.clock,
                  CupertinoIcons.arrow_down_left_circle,
                  CupertinoIcons.bell_fill,
                  CupertinoIcons.bag_fill_badge_plus,
                  CupertinoIcons.cloud_fill,
                  CupertinoIcons.arrow_up_left,
                  CupertinoIcons.battery_75_percent,
                  CupertinoIcons.app_fill,
                  CupertinoIcons.camera_fill,
                  CupertinoIcons.clear_circled_solid,
                  CupertinoIcons.bolt,
                  CupertinoIcons.archivebox_fill,
                  CupertinoIcons.battery_25,
                  CupertinoIcons.arrow_left_circle,
                  CupertinoIcons.arrow_up_left_circle_fill,
                  CupertinoIcons.bell_slash,
                  CupertinoIcons.arrow_down,
                  CupertinoIcons.app_badge_fill,
                  CupertinoIcons.cloud_bolt,
                  CupertinoIcons.arrow_down_right_circle,
                  CupertinoIcons.arrow_up,
                  CupertinoIcons.arrow_up_left_circle,
                  CupertinoIcons.arrow_down_circle_fill,
                  CupertinoIcons.add_circled_solid,
                  CupertinoIcons.arrow_down_doc_fill,
                  CupertinoIcons.app_badge,
                  CupertinoIcons.arrow_right_circle,
                  CupertinoIcons.bag_fill_badge_minus,
                  CupertinoIcons.arrow_right_circle_fill,
                  CupertinoIcons.cloud_download,
                  CupertinoIcons.cloud_sun_fill,
                  CupertinoIcons.arrow_down_left_circle_fill,
                  CupertinoIcons.arrow_up_right_circle,
                  CupertinoIcons.arrow_up_right_circle_fill,
                  CupertinoIcons.arrow_left_circle_fill,
                  CupertinoIcons.bolt_circle_fill,
                   CupertinoIcons.cloud,
                  CupertinoIcons.chevron_up,
                  CupertinoIcons.bag_fill,
                  CupertinoIcons.arrow_up_doc_fill,
                  CupertinoIcons.camera,
                  CupertinoIcons.bookmark_fill,
                  CupertinoIcons.chevron_back,
                  CupertinoIcons.cloud_sun,
                  CupertinoIcons.circle,
                  CupertinoIcons.battery_0,
                  CupertinoIcons.chat_bubble,
                  CupertinoIcons.chevron_down,
                  CupertinoIcons.cloud_upload_fill,
                  CupertinoIcons.cart,
                  CupertinoIcons.bell,
                  CupertinoIcons.arrow_right,
                  CupertinoIcons.book_fill,
                  CupertinoIcons.cloud_rain_fill,
                  CupertinoIcons.arrow_left_circle_fill,
                  CupertinoIcons.clear,
                  CupertinoIcons.battery_charging,
                  CupertinoIcons.check_mark_circled,
                  CupertinoIcons.arrow_down_doc,
                  CupertinoIcons.briefcase_fill,
                  CupertinoIcons.car_detailed,
                  CupertinoIcons.cloud_snow,
                  CupertinoIcons.chevron_compact_left,
                  CupertinoIcons.circle_fill,
                  CupertinoIcons.book,
                  CupertinoIcons.chat_bubble_2,
                  CupertinoIcons.cloud_download_fill,
                  CupertinoIcons.chevron_right,
                  CupertinoIcons.arrow_up_right,
                  CupertinoIcons.check_mark,
                  CupertinoIcons.alarm_fill,
                  CupertinoIcons.cloud_upload,
                  CupertinoIcons.clear_circled,
                  CupertinoIcons.arrow_down_circle,
                  CupertinoIcons.calendar_today,
                  CupertinoIcons.add_circled,
                  CupertinoIcons.bag_badge_plus,
                  CupertinoIcons.battery_empty,
                  CupertinoIcons.chevron_forward,
                  CupertinoIcons.bookmark,
                  CupertinoIcons.arrow_down_right_circle_fill,
                  CupertinoIcons.battery_full,
                  CupertinoIcons.bag,
                  CupertinoIcons.chat_bubble_fill,
                  CupertinoIcons.add,
                  CupertinoIcons.clock_fill,
                  CupertinoIcons.cloud_snow_fill,
                  CupertinoIcons.cart_fill,
                  CupertinoIcons.bolt_circle,
                  CupertinoIcons.alarm,
                  CupertinoIcons.chat_bubble_2_fill,
                  CupertinoIcons.check_mark_circled_solid,
                  CupertinoIcons.chevron_compact_down,
                  CupertinoIcons.arrow_up_circle,
                  CupertinoIcons.arrow_left,
                  CupertinoIcons.app,
                  CupertinoIcons.bolt_fill,
                  CupertinoIcons.arrow_clockwise,
                  CupertinoIcons.calendar,
                  CupertinoIcons.cloud_rain,
                  CupertinoIcons.chevron_compact_right,
                  CupertinoIcons.bag_badge_minus,
                  CupertinoIcons.arrow_up_doc,
                  CupertinoIcons.arrow_down_left,
                  CupertinoIcons.arrow_up_circle_fill,
                  CupertinoIcons.arrow_down_right,
                  CupertinoIcons.bell_slash_fill,
                  CupertinoIcons.bolt_badge_a,
                  CupertinoIcons.archivebox,
                  CupertinoIcons.chevron_compact_up,
                  CupertinoIcons.clock,
                  CupertinoIcons.arrow_down_left_circle,
                  CupertinoIcons.bell_fill,
                  CupertinoIcons.bag_fill_badge_plus,
                  CupertinoIcons.cloud_fill,
                  CupertinoIcons.arrow_up_left,
                  CupertinoIcons.battery_75_percent,
                  CupertinoIcons.app_fill,
                  CupertinoIcons.camera_fill,
                  CupertinoIcons.clear_circled_solid,
                  CupertinoIcons.bolt,
                  CupertinoIcons.archivebox_fill,
                  CupertinoIcons.battery_25,
                  CupertinoIcons.arrow_left_circle,
                  CupertinoIcons.arrow_up_left_circle_fill,
                  CupertinoIcons.bell_slash,
                  CupertinoIcons.arrow_down,
                  CupertinoIcons.app_badge_fill,
                  CupertinoIcons.cloud_bolt,
                  CupertinoIcons.arrow_down_right_circle,
                  CupertinoIcons.arrow_up,
                  CupertinoIcons.arrow_up_left_circle,
                  CupertinoIcons.arrow_down_circle_fill,
                  CupertinoIcons.add_circled_solid,
                  CupertinoIcons.arrow_down_doc_fill,
                  CupertinoIcons.app_badge,
                  CupertinoIcons.arrow_right_circle,
                  CupertinoIcons.bag_fill_badge_minus,
                  CupertinoIcons.arrow_right_circle_fill,
                  CupertinoIcons.cloud_download,
                  CupertinoIcons.cloud_sun_fill,
                  CupertinoIcons.arrow_down_left_circle_fill,
                  CupertinoIcons.arrow_up_right_circle,
                  CupertinoIcons.arrow_up_right_circle_fill,
                  CupertinoIcons.arrow_left_circle_fill,
                  CupertinoIcons.bolt_circle_fill,
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
